name: stacks.js

on:
  push:
  pull_request:

jobs:
  code_checks:
    name: Code Checks
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - uses: actions/checkout@v2

      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Restore lerna cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm i

      - name: Bootstrap
        run: npm run bootstrap

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Tests
        run: npm run lerna run test --stream --parallel -- -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
